# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test-Tequila-Chemistry

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: madness basics
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -e .
        cd tests
        ls
        pytest test_chemistry_madness.py
        cd ../
    - name: Install and test madness interface
      run: |
        echo "done"
        
        sudo echo "#!/bin/bash" > pno_integrals
        sudo echo "name=\$(docker run -t -d kottmanj/mra-pno)" >> pno_integrals
        sudo echo "sudo docker cp input \$name:/" >> pno_integrals
        sudo echo "sudo docker exec \$name pno_integrals > pno.out" >> pno_integrals
        sudo echo "sudo docker cp \$name:molecule_htensor.bin ." >> pno_integrals 
        sudo echo "sudo docker cp \$name:molecule_gtensor.bin ." >> pno_integrals
        sudo echo "sudo docker cp \$name:pnoinfo.txt ." >> pno_integrals
        sudo echo "sudo docker stop \$name" >> pno_integrals
        sudo echo "sudo docker rm \$name" >> pno_integrals
        echo "asd"
        
        cat pno_integrals

        chmod +X pno_integrals
        #sudo ln -s pno_integrals /usr/sbin/pno_integrals
        #echo $PATH
        sudo mkdir /madroot
        sudo mkdir /madroot/src
        sudo mkdir /madroot/src/apps/
        sudo mkdir /madroot/src/apps/pno/
        sudo mv pno_integrals /madroot/src/apps/pno/
        export MAD_ROOT_DIR=/madroot/
        echo $MAD_ROOT_DIR
        chmod +x ${MAD_ROOT_DIR}/src/apps/pno/pno_integrals
        ls -l ${MAD_ROOT_DIR}/src/apps/pno/

        echo "get docker image"
        sudo docker pull kottmanj/mra-pno
        sudo docker images


        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -e .
        python -m pip install pytest
        cd tests
        python test_chemistry_madness.py
        pytest test_chemistry_madness.py
        cd ../

    - name: Install and test Psi4 interface
      run: |
        ver=$(python -c"import sys; print(sys.version_info.minor)")
        fullver=$(echo "3.$ver")
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
        export CONDABASE=$HOME/miniconda
        bash miniconda.sh -b -p $CONDABASE
        export PATH=$CONDABASE:$PATH
        export PATH="$CONDABASE/bin:$PATH"
        conda update -q conda
        conda create -n test_psi4 python=$fullver
        conda init bash
        bash
        source $HOME/.bashrc
        source $CONDABASE/bin/activate
        conda activate test_psi4
        conda install psi4 -c psi4
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -e .
        python -m pip install pyscf
        python -m pip install 'h5py <= 3.1'
        cd tests
        ls
        pytest test_chemistry.py
        pytest test_adapt.py
        cd ../
